name: Build

on: push

jobs:
  build_on_win:
    runs-on: ubuntu-latest

    steps:  
      - uses: actions/checkout@v2    
      - name: download pytest
        run:
          pip install pytest
      
      
      - name: Build make
        run:
          make      
      
      - name: Build test
        run: 
          make test
          