name: Build

on: push

jobs:
  build:
    runs-on: windows 10

    steps:  
      - uses: actions/checkout@v2    
      - name: download pytest
        run:
          pip install pytest
      
      - name: download tkinker
        run:
          pip install tkinker
      
      - name: Build make
        run:
          make      
      
      - name: Build test
        run: 
          make test
          